export enum EExperience {
  INTERN = 'INTERN',
  JUNIOR = 'JUNIOR',
  SENIOR = 'SENIOR',
  LEAD = 'LEAD',
  MANAGER = 'MANAGER',
}

export enum ERole {
  BACKEND = 'BACKEND',
  FRONTEND = 'FRONTEND',
  FULLSTACK = 'FULLSTACK',
  DEVOPS = 'DEVOPS',
}

export enum EDomain {
  SOFTWARE_ENGINEER = 'SOFTWARE_ENGINEER',
  DEVOPS_ENGINEER = 'DEVOPS_ENGINEER',
  DATA_SCIENCE = 'DATA_SCIENCE',
  PRODUCT_MANAGEMENT = 'PRODUCT_MANAGEMENT',
}

export enum EProgrammingLanguage {
  PYTHON = 'PYTHON',
  JAVA = 'JAVA',
  JS = 'JS',
  TYPESCRIPT = 'TYPESCRIPT',
  CPP = 'CPP',
  CSHARP = 'CSHARP',
  GO = 'GO',
  RUST = 'RUST',
  SWIFT = 'SWIFT',
  KOTLIN = 'KOTLIN',
}

export enum ETargetCompany {
  GOOGLE = 'GOOGLE',
  MICROSOFT = 'MICROSOFT',
  FACEBOOK = 'FACEBOOK',
  AMAZON = 'AMAZON',
  APPLE = 'APPLE',
  NETFLIX = 'NETFLIX',
  UBER = 'UBER',
  AIRBNB = 'AIRBNB',
  TWITTER = 'TWITTER',
  LINKEDIN = 'LINKEDIN',
  SALESFORCE = 'SALESFORCE',
  ADOBE = 'ADOBE',
}

export enum EQuestionType {
  INITIAL = 'INITIAL',
  FOLLOW_UP = 'FOLLOW_UP',
}

export enum ESolutionType {
  CODE_SOLUTION = 'CODE_SOLUTION',
  WHITEBOARD_IMAGE = 'WHITEBOARD_IMAGE',
  CODE_REPO_WITH_OUTPUT = 'CODE_REPO_WITH_OUTPUT',
  TEXT_ANSWER = 'TEXT_ANSWER',
}

export enum EInterviewRound {
  TECHNICAL_ROUND_1 = 'TECHNICAL_ROUND_1',
  TECHNICAL_ROUND_2 = 'TECHNICAL_ROUND_2',
  SYSTEM_DESIGN = 'SYSTEM_DESIGN',
  BEHAVIORAL = 'BEHAVIORAL',
  MANAGERIAL_ROUND = 'MANAGERIAL_ROUND',
  HR_ROUND = 'HR_ROUND',
}
