/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/interviewer_avatar.glb -o src/components/Avatar/index.jsx 
*/
import React, { useEffect, useRef } from 'react';
import { useGraph } from '@react-three/fiber';
import { useAnimations, useFBX, useGLTF } from '@react-three/drei';
import * as SkeletonUtils from 'three/examples/jsm/utils/SkeletonUtils';
import { animations } from '@/constants/interviewer';
import { useAtomValue } from 'jotai';
import {
  isSpeakingAtom,
  isInterruptionSpeakingAtom,
} from '../InterviewScene/AnswerBoardTools/atoms';
import { FE_ASSETS } from '@/constants/imageAssets';

export function InterviewerAvatar({ ...props }) {
  const { scene } = useGLTF(FE_ASSETS.MISC.INTERVIEWER_AVATAR);
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { animations: meetingAnimations } = useFBX(FE_ASSETS.MISC.MEETING_ANIMATION);
  const { animations: sittingIdleAnimations } = useFBX(FE_ASSETS.MISC.SITTING_IDLE_ANIMATION);
  const { animations: talkingAnimations } = useFBX(FE_ASSETS.MISC.TALKING_ANIMATION);

  // Clone the animations to avoid mutating the original
  const processedAnimations = React.useMemo(() => {
    const meeting = meetingAnimations[0].clone();
    const sittingIdle = sittingIdleAnimations[0].clone();
    const talking = talkingAnimations[0].clone();

    meeting.name = animations.Meeting;
    sittingIdle.name = animations.SittingIdle;
    talking.name = animations.Talking;

    return [meeting, sittingIdle, talking];
  }, [meetingAnimations, sittingIdleAnimations, talkingAnimations]);

  const group = useRef();
  const isSpeakingQuestion = useAtomValue(isSpeakingAtom);
  const isSpeakingInterruption = useAtomValue(isInterruptionSpeakingAtom);
  const isSpeaking = isSpeakingQuestion || isSpeakingInterruption;
  const { actions } = useAnimations(processedAnimations, group);

  useEffect(() => {
    let animationFrame;
    let lastToggle = 0;

    // Change animation when speaking state changes
    if (isSpeaking) {
      actions[animations.SittingIdle]?.fadeOut(0.5);
      actions[animations.Meeting]?.reset().fadeIn(0.5).play();
    } else {
      actions[animations.Meeting]?.fadeOut(0.5);
      actions[animations.SittingIdle]?.reset().fadeIn(0.5).play();
    }

    const animateMouth = timestamp => {
      if (!isSpeaking) return;

      // Random interval between 100ms and 300ms
      if (timestamp - lastToggle > Math.random() * 200 + 100) {
        const mouthOpenIndex = nodes.Wolf3D_Head.morphTargetDictionary['mouthOpen'];
        if (mouthOpenIndex !== undefined) {
          let mouthValue = nodes.Wolf3D_Head.morphTargetInfluences[mouthOpenIndex];
          mouthValue = mouthValue === 1 ? 0 : 1;
          nodes.Wolf3D_Head.morphTargetInfluences[mouthOpenIndex] = mouthValue;
          lastToggle = timestamp;
        }
      }

      animationFrame = requestAnimationFrame(animateMouth);
    };

    if (isSpeaking) {
      animationFrame = requestAnimationFrame(animateMouth);
    } else {
      const mouthOpenIndex = nodes.Wolf3D_Head.morphTargetDictionary['mouthOpen'];
      if (mouthOpenIndex !== undefined) {
        nodes.Wolf3D_Head.morphTargetInfluences[mouthOpenIndex] = 0;
      }
    }

    return () => {
      if (animationFrame) {
        cancelAnimationFrame(animationFrame);
      }
      const mouthOpenIndex = nodes.Wolf3D_Head.morphTargetDictionary['mouthOpen'];
      if (mouthOpenIndex !== undefined) {
        nodes.Wolf3D_Head.morphTargetInfluences[mouthOpenIndex] = 0;
      }
    };
  }, [isSpeaking, nodes.Wolf3D_Head, actions]);

  return (
    <group rotation-x={-Math.PI / 2}>
      <group ref={group} {...props} dispose={null}>
        <primitive object={nodes.Hips} />
        <skinnedMesh
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
        <skinnedMesh
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        />
        <skinnedMesh
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload(FE_ASSETS.MISC.INTERVIEWER_AVATAR);
